### ISSUE TITLE
Repeating NPE when joining after a reload or restart

### ISSUE THREAD

**Issue by digitalkitten** [Indyuce/mmocore#1]
There is a repeating (that is, repeating every second) NPE in MMOCore.java when joining after a reload or restart. This same thing happens when remaining in-game during a /rpg reload.

```
[13:12:00] [Craft Scheduler Thread - 12/WARN]: [MMOCore] Plugin MMOCore vBETA6 generated an exception while executing task 65
java.lang.NullPointerException: null
        at net.Indyuce.mmocore.MMOCore$1.run(MMOCore.java:218) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-d05d3c1-7ffb2a2]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-d05d3c1-7ffb2a2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by digitalkitten** [comment]
```
[13:22:02] [Craft Scheduler Thread - 3/WARN]: [MMOCore] Plugin MMOCore vBETA6 generated an exception while executing task 65
java.lang.NullPointerException: null
        at net.Indyuce.mmocore.MMOCore$1.run(MMOCore.java:218) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-d05d3c1-7ffb2a2]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-d05d3c1-7ffb2a2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[13:22:02] [Server thread/INFO]: digitalkitten95 lost connection: Disconnected
[13:22:03] [Server thread/INFO]: digitalkitten95 left the game
```

Same error when doing /class after a restart or reload.

**Comment by Indyuce** [comment]
Most of repeating task issues are due to startup or join errors, can you look for that on your console?
