### ISSUE TITLE
New update spams errors

### ISSUE THREAD

**Issue by HRZNzero** [Indyuce/mmocore#19]
Newest versions from mythicmobs website (30.12.2019, 17:59, CET)

[17:58:41] [Server thread/INFO]: [DEBUG MiracleTournaments] - Placed Block: AIR
[17:58:46] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to MMOLib v1.0.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:229) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:918) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:805) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:761) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:950) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1622) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:862) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1026) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:785) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:657) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1517) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1878) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at net.mmogroup.mmolib.api.player.MMOData.getPlayer(MMOData.java:61) ~[?:?]
        at net.mmogroup.mmolib.api.event.MMODataEvent.<init>(MMODataEvent.java:11) ~[?:?]
        at net.mmogroup.mmolib.api.event.PlayerAttackEvent.<init>(PlayerAttackEvent.java:19) ~[?:?]
        at net.mmogroup.mmolib.listener.event.PlayerAttackEventListener.a(PlayerAttackEventListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor434.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        ... 29 more

Minecraft spigot 1.15.1

**Comment by Indyuce** [comment]
Make sure your MMOCore, MMOItems and MMOLib builds are up to date.
